stages:
  - build
  - deploy

.build-conda: &build-conda
  stage: build
  script:
    - conda build ./conda/camera --prefix-length=80 --output-folder=dist/ --channel=http://bcu-ci.esrf.fr/stable
  artifacts:
    paths:
      - dist/
  tags:
    - conda

build-win:
  <<: *build-conda
  tags:
    - win

build-noarch:
  <<: *build-conda

deploy_devel:
  stage: deploy
  environment:
    name: devel/$CI_COMMIT_REF_NAME
    url: http://bcu-ci.esrf.fr/devel
  dependencies:
    - build-win
    - build-noarch
  script:
    - cp -Rf dist/* /conda-devel/
    - conda index /conda-devel/
  tags:
    - conda
    - linux
  only:
    - branches
  except:
    - stable
  when: manual

deploy_stable:
  stage: deploy
  environment:
    name: production
    url: http://bcu-ci.esrf.fr/stable
  dependencies:
    - build-win
    - build-noarch
  script:
    - cp -Rf dist/* /conda/
    - conda index /conda/
  tags:
    - conda
    - linux
  only:
    - tags
    - stable
